# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='user',
        ),
    ]
