# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180919_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
