# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_publisher_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.CharField(max_length=56)),
            ],
        ),
    ]
