# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='home_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Home'),
        ),
    ]
