# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_publisher_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='home_id',
            new_name='home',
        ),
    ]
