# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20180920_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='dep',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
